@registry=onetocny001.azurecr.io
@url=https://{{registry}}/oauth2/exchange
@tenant=7e527386-53a9-4ca0-8a2e-981cf1f68693
@aad_access_token=xxx

# @name acr_refresh_token_request
POST {{url}}
Content-Type: application/x-www-form-urlencoded

grant_type=access_token&service={{registry}}&tenant={{tenant}}&access_token={{aad_access_token}}

###

@acr_refresh_token = {{acr_refresh_token_request.response.body.refresh_token}}
@scope=registry:catalog:*

# @name acr_access_token_request
POST https://{{registry}}/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&service={{registry}}&scope={{scope}}&refresh_token={{acr_refresh_token}}

###

@acr_access_token = {{acr_access_token_request.response.body.access_token}}


# @name acr_catalog
GET https://{{registry}}/v2/_catalog
#Authorization: Bearer {{acr_access_token}}