@buildId = baa48759-cdc2-4204-87e1-6350edadd007%3A1


### Gandalf
GET https://vsrm.codedev.ms/onetocny/_apis/Release/projects
    ?artifactType=Build
    &artifactSourceId={{buildId}}
Authorization: Basic :ugm5sdh3vu7dhbcnuxat5k4hxrzrwscgavt5ldojsp4x6yu2ur6a



### Saruman
GET https://vsrm.codedev.ms/onetocny/_apis/Release/projects
    ?artifactType=Build
    &artifactSourceId={{buildId}}
Authorization: Basic :ntpxopii76edwmncdqpqdy6rhdhayr5pbtlvxfarl4sedvfykvza

