@endpointId = f4e3cc94-aa49-486d-b7a1-8ac31b407991

GET {{base_url}}/{{organization}}/{{project}}/_apis/serviceendpoint/{{endpointId}}/executionhistory?api-version=7.0
Authorization: Basic :{{PAT}}
Content-type: application/json
Accept: application/json;api-version=6.0-preview.1;excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true
